/*
 * Long-form case-study content, keyed by project slug.
 *
 * Why this lives apart from data/projects.ts:
 *
 *  - `description` in projects.ts is *display* copy. It is rendered on the
 *    portfolio card, in the showcase carousel and at the top of the case
 *    study, so it has to stay short. It was previously doing double duty as
 *    the meta description too, which is why most project pages shipped
 *    170–260 character snippets that Google truncated mid-sentence.
 *
 *  - The "Key Development Areas" list used to be generated by splitting that
 *    same `description` on sentence boundaries, so the bullets were a verbatim
 *    reprint of the paragraph directly above them. `highlights` replaces that
 *    with content that is actually distinct.
 *
 *  - 27 pages sharing one ~140-word template is a thin/duplicate-content
 *    pattern. `problem` / `approach` / `outcome` / `stackRationale` give each
 *    page genuinely unique body copy in the 300–600 word range.
 *
 * NOTE ON `updatedAt`: these are best-estimate dates, set so the sitemap can
 * emit a meaningful per-URL <lastmod> instead of stamping all 28 URLs with the
 * build time. Correct any that are wrong — a lastmod that misrepresents when
 * the page actually changed is worse than none.
 */

export interface CaseStudy {
  /** ≤155 chars. Meta description only — never rendered on the page. */
  seoDescription: string;
  /** ISO date (YYYY-MM-DD) of the last substantive change to this project. */
  updatedAt: string;
  /** Distinct from `description` — never a re-split of it. */
  highlights: string[];
  /** What the client was up against before the work started. */
  problem: string;
  /** What was actually built, in implementation terms. */
  approach: string;
  /** What changed as a result. */
  outcome: string;
  /** Why this stack, rather than the obvious alternative. */
  stackRationale: string;
}

export const caseStudies: Record<string, CaseStudy> = {
  // ── Shopify ─────────────────────────────────────────────────────
  'image-1993-pakistan': {
    seoDescription:
      'Image 1993 Pakistan — Shopify theme development and regional performance tuning for a premium fashion retailer, by Munib Ahmad.',
    updatedAt: '2025-11-18',
    highlights: [
      'Region-aware variant logic so a single product catalogue serves three storefronts without duplicate SKUs',
      'AJAX cart drawer rebuilt to update line items without a full page reload',
      'Local payment gateway wired into checkout with a fallback path for failed handshakes',
      'Image delivery moved to responsive srcsets sized against real device breakpoints',
    ],
    problem:
      'Image 1993 runs one fashion brand across three national storefronts, and Pakistan is the highest-traffic of the three. The theme it inherited treated region as an afterthought: prices, sizing conventions and payment options were hard-coded for a single market, so every regional difference had been solved by duplicating products. The catalogue had drifted out of sync, and page weight from unoptimised lookbook imagery made the store noticeably slow on the mid-range Android handsets that make up most of its traffic.',
    approach:
      'I rebuilt the variant layer so region is a property of the storefront rather than of the product, which collapsed the duplicated SKUs back into a single source of truth. The cart was converted to an AJAX drawer that mutates line items in place, removing the full page reload that had been sitting between every add-to-cart and the next interaction. Payment configuration was moved behind a Liquid-level capability check so the local gateway renders only where it is actually available, with a graceful fallback when the handshake fails. On the asset side, I replaced fixed-width imagery with responsive srcsets generated against the breakpoints the analytics actually showed, and deferred the below-fold lookbook sections so they no longer compete with the hero for bandwidth.',
    outcome:
      'The storefront now serves the Pakistani market from the same catalogue as its sibling sites without the manual reconciliation that used to be required after every product drop. Add-to-cart is instant rather than a page navigation, and the initial render no longer waits on full-resolution lookbook images. The regional configuration is data-driven, so opening a fourth market is a settings change rather than another theme fork.',
    stackRationale:
      'Staying inside Liquid and the native cart API, rather than reaching for a headless rebuild, kept the store fully operable from the Shopify admin — the client edits merchandising without a deploy. A headless frontend would have bought marginally faster transitions at the cost of handing every content change back to a developer, which for a team that re-merchandises weekly is the wrong trade.',
  },

  'image-1993-usa': {
    seoDescription:
      'Image 1993 USA — Shopify international storefront build with multi-currency, cross-border CDN delivery and shipping logic, by Munib Ahmad.',
    updatedAt: '2025-10-02',
    highlights: [
      'Currency presentment wired to the storefront locale rather than a client-side converter',
      'Shipping matrix mapped to US zones with weight banding at the rate-calculation layer',
      'CDN edge configuration tuned for North American round-trip times',
      'Automated post-purchase sequences triggered on order tags, not on manual export',
    ],
    problem:
      'The US storefront was the brand\'s first expansion outside its home market and it launched with the home market\'s assumptions intact. Prices were converted in the browser after render, so customers watched values change under them; shipping rates were a flat estimate that under-charged heavy orders and over-charged light ones; and every asset was still being served from an origin optimised for South Asian traffic, which added a full round trip for every American visitor.',
    approach:
      'Currency presentment was moved to Shopify Markets so the storefront renders the correct currency server-side, eliminating the visible conversion flicker and the rounding mismatches at checkout. I rebuilt the shipping configuration as a real rate matrix — US zones crossed with weight bands — rather than a single flat estimate, so the quoted cost reflects what fulfilment actually pays. CDN behaviour was retuned for North American edge nodes, and cache headers were set so repeat visitors pull almost the entire theme from cache. Post-purchase automation was rewired to fire on order tags applied at checkout, replacing a manual export-and-upload step the team had been doing by hand.',
    outcome:
      'The store now presents stable, correct pricing from first paint, and quoted shipping matches fulfilment cost closely enough that the margin leak on heavy orders closed. Asset delivery to US visitors no longer crosses continents on every request. The automation running off order tags removed a recurring manual task from the operations team\'s week.',
    stackRationale:
      'Shopify Markets handles currency and tax presentment natively, so building a bespoke converter would have meant maintaining exchange-rate logic that the platform already keeps correct. The one place I did write custom logic — the shipping matrix — is the place where the native defaults genuinely could not express the brand\'s cost structure.',
  },

  'image-1993-uk': {
    seoDescription:
      'Image 1993 UK — Shopify regional build with VAT handling, multi-currency display and optimised lookbook rendering, by Munib Ahmad.',
    updatedAt: '2025-09-24',
    highlights: [
      'VAT-inclusive pricing displayed at the point of decision rather than revealed at checkout',
      'Lookbook imagery progressively decoded so hero content is never blocked',
      'Size conversion surfaced inline against UK sizing conventions',
      'Locale formatting for dates, currency and address fields driven by the storefront locale',
    ],
    problem:
      'UK shoppers expect to see the price they will actually pay, VAT included, from the product page onward. The storefront was showing ex-VAT figures and adding tax at checkout, which read as a late price increase and correlated with drop-off at the final step. On top of that, the brand\'s lookbooks are its main merchandising tool and the pages were loading every image at full resolution up front, so the hero sat blank on slower connections while decorative photography downloaded.',
    approach:
      'I switched the storefront to VAT-inclusive presentment so the figure on the product card is the figure at checkout, and reworked the price display components to carry a clear tax note rather than leaving the basis ambiguous. Lookbook sections were rebuilt around progressive decoding with explicit dimensions on every image, which both unblocks the hero and removes the layout shift that had been happening as photographs arrived. Size conversion was surfaced inline next to the variant selector, mapping the brand\'s native sizing to UK conventions at the point where the choice is made rather than in a modal nobody opened. Locale-dependent formatting — dates, currency symbols, address field order — was bound to the storefront locale instead of being hard-coded.',
    outcome:
      'Pricing is now consistent from browse to checkout, which removed the surprise that was costing conversions at the last step. Hero content paints without waiting on below-fold photography, and the reserved image dimensions eliminated the cumulative layout shift the lookbooks had been introducing. Size questions are answered inline, reducing a recurring pre-purchase support thread.',
    stackRationale:
      'VAT presentment is a Shopify Markets setting rather than a theme concern, so pushing it down to the platform means it stays correct when rates change. Keeping the size conversion in Liquid rather than a third-party app avoided adding another render-blocking script to a page whose whole problem was render-blocking assets.',
  },

  'panjnad-shop': {
    seoDescription:
      'Panjnad Shop — custom Shopify Liquid storefront with asset compression and checkout conversion optimisation, by Munib Ahmad.',
    updatedAt: '2025-08-14',
    highlights: [
      'Theme rebuilt from a custom Liquid base rather than layering overrides onto a stock theme',
      'Asset pipeline reworked to ship compressed, correctly-sized media',
      'Checkout flow shortened by removing steps that collected data nobody used',
      'Collection templates driven by metafields so merchandising changes need no code',
    ],
    problem:
      'The store had accumulated the usual sediment of a long-running Shopify build: a stock theme with several years of overrides stacked on top, apps installed for single features and never removed, and an asset folder full of uncompressed uploads. Nothing was individually broken, but the cumulative weight made the store slow, and the checkout had grown extra fields that existed only because someone had once asked for them.',
    approach:
      'Rather than continue patching, I rebuilt the theme on a clean custom Liquid base, porting across only the sections that were actually in use. That alone removed a large amount of dead CSS and JavaScript inherited from features the store no longer ran. The asset pipeline was reworked so uploads are compressed and correctly sized before they ship, instead of full-resolution originals being scaled down in the browser. I audited the checkout against what the fulfilment team genuinely needed and removed the fields that were being collected and never read. Collection templates were rebuilt to read from metafields, so merchandising rules live in the admin rather than in theme code.',
    outcome:
      'The store ships substantially less code and media per page than the version it replaced, and the remaining code corresponds to features that are actually in use. The shortened checkout removed friction at the step where abandonment is most expensive. Because merchandising now reads from metafields, routine catalogue changes no longer queue behind developer availability.',
    stackRationale:
      'A rebuild is usually the wrong instinct — it is slower than patching and risks regressions. It was right here because the override layer had grown larger than the theme underneath it, so every new change was becoming more expensive than the last. Custom Liquid over a stock theme meant no inherited weight for features the store does not use.',
  },

  'saya-usa': {
    seoDescription:
      'Saya USA — international Shopify storefront with modular product templates, multi-currency and fast collection filters, by Munib Ahmad.',
    updatedAt: '2025-07-30',
    highlights: [
      'Product templates composed from reusable sections rather than per-category duplicates',
      'Collection filtering moved server-side so large catalogues stay responsive',
      'Multi-currency presentment tied to the storefront locale',
      'Structured data emitted per product for richer search results',
    ],
    problem:
      'Saya sells apparel internationally across a catalogue broad enough that filtering is how most customers actually navigate. The existing filter implementation ran client-side over the full product list, which was acceptable at a few dozen items and visibly slow past a few hundred. Meanwhile the product page had been duplicated per category, so a change to the size guide meant editing the same block in several templates and hoping none were missed.',
    approach:
      'I collapsed the duplicated product templates into a single template composed from reusable sections, with per-category differences expressed as section settings rather than as separate files. Filtering was moved to Shopify\'s server-side filtering API, so the browser requests a filtered collection instead of downloading everything and hiding most of it. Currency presentment was bound to the storefront locale rather than guessed from IP, which removed a class of mismatch where a visitor saw one currency and was charged in another. I also added per-product structured data so search engines can read price, availability and review data directly.',
    outcome:
      'Filtering stays responsive regardless of how far the catalogue grows, because the work now happens at the platform layer instead of in the visitor\'s browser. Shared components like the size guide are edited once and take effect everywhere, which closed the drift that had crept in between category templates. Products are now eligible for rich results in search rather than appearing as plain links.',
    stackRationale:
      'Server-side filtering is the less flexible option — you are bound to what the platform supports — but that constraint is exactly why it scales. A bespoke client-side filter would have offered more control over the UI and degraded predictably as the catalogue grew, which is the wrong shape of trade-off for a store that intends to keep adding products.',
  },

  'silent-luxury': {
    seoDescription:
      'Silent Luxury — minimal Shopify storefront for a luxury streetwear label, with bespoke grid layouts and editorial detail, by Munib Ahmad.',
    updatedAt: '2025-06-21',
    highlights: [
      'Editorial grid built on CSS grid with deliberate asymmetry rather than a uniform product wall',
      'Micro-interactions restricted to transform and opacity so they never trigger layout',
      'Typography scale set in fluid units so headings hold their proportions across breakpoints',
      'Colour and spacing tokens centralised, making brand adjustments a single-file change',
    ],
    problem:
      'Silent Luxury is positioned against the visual language of mass-market streetwear, which meant the default Shopify grid — uniform tiles, edge-to-edge, every product weighted equally — worked directly against the brand. The client needed a storefront that read as editorial rather than catalogue, without paying for that in performance, since the audience skews mobile and the previous attempt at a "premium" feel had been a carousel-heavy build that stuttered on scroll.',
    approach:
      'The collection grid was rebuilt on CSS grid with intentional asymmetry, so featured pieces occupy larger cells and the eye has somewhere to travel instead of scanning a uniform wall. Every micro-interaction was constrained to transform and opacity, the two properties the browser can animate without recalculating layout, which is what keeps the scroll smooth on mid-range phones. Typography was set on a fluid scale so the relationship between display and body sizes holds at every breakpoint rather than collapsing on small screens. Colour, spacing and radius values were pulled into a single token layer, so brand-level adjustments propagate without hunting through section files.',
    outcome:
      'The storefront reads as an editorial piece while remaining a standard Shopify store the client can merchandise themselves. The animation constraint means the visual polish costs effectively nothing on scroll performance, which is where the previous premium-feel attempt had failed. Tokenised design values made subsequent brand tweaks fast enough to do in a single session.',
    stackRationale:
      'This is the kind of brief that invites an animation library, and I deliberately did not add one. Everything here is achievable with CSS transitions on compositor-friendly properties; importing a library would have added payload to a mobile-first store in exchange for capabilities the design never called for.',
  },

  'vera-world-international': {
    seoDescription:
      'Vera World — cross-border Shopify build with dynamic size guides, cart drawer and AJAX add-to-cart, by Munib Ahmad.',
    updatedAt: '2025-05-19',
    highlights: [
      'Size guide rendered per product from metafields instead of one generic modal',
      'Slide-out cart drawer that keeps the customer on the page through add-to-cart',
      'Cross-border shipping expectations surfaced before checkout, not at it',
      'Inventory state reflected on the variant selector so sold-out options read clearly',
    ],
    problem:
      'Vera World ships a boutique fashion catalogue across borders, which puts sizing and shipping expectations at the centre of the buying decision. The store had one generic size chart behind a modal, covering garments cut to different specifications, so it was frequently wrong and customers had learned to ignore it. Returns driven by fit were the single largest source of support load. Compounding it, cross-border shipping cost and timing only appeared at checkout, so customers were discovering the real cost after investing in the process.',
    approach:
      'I moved size data into per-product metafields so the guide renders the measurements for the garment being viewed, rather than a catalogue-wide approximation, and surfaced it inline beside the variant selector instead of behind a modal. The cart became a slide-out drawer so adding an item no longer navigates away mid-browse. Shipping expectations were pulled forward: destination-aware cost and timing estimates now appear on the product page, so the cross-border reality is part of the decision rather than a surprise at the end. The variant selector was reworked to reflect inventory state directly, so unavailable combinations read as unavailable instead of failing after selection.',
    outcome:
      'Fit guidance is now specific enough to be trusted, which addresses the root cause of the return volume rather than the symptom. Customers see cross-border cost and timing while they are still deciding, so the checkout step stops being where expectations get corrected. Browsing continuity through add-to-cart removed the navigation break that had been interrupting multi-item sessions.',
    stackRationale:
      'Metafields were the right home for size data because they keep it attached to the product and editable by the merchandising team. A size-guide app would have been faster to install and would have put the data in a third-party system, where it drifts out of sync with the catalogue exactly as the original generic chart had.',
  },

  'route-2-health': {
    seoDescription:
      'Route 2 Health — Shopify healthcare storefront with trust signals, ingredient disclosure and compliant checkout, by Munib Ahmad.',
    updatedAt: '2025-04-16',
    highlights: [
      'Ingredient and dosage data structured per product rather than buried in description HTML',
      'Certification and trust signals placed at the decision point, not in the footer',
      'Accessible accordions for long-form regulatory copy',
      'Checkout configured to meet disclosure requirements for health products',
    ],
    problem:
      'Selling health and wellness products carries disclosure obligations that a standard e-commerce theme has no concept of. Route 2 Health had been meeting them by pasting long blocks of formatted HTML into product descriptions, which made the information technically present but practically unreadable, impossible to query, and prone to breaking the page layout when someone pasted from a word processor. Trust signals — certifications, sourcing, testing — were in the footer, far from where purchase decisions actually happen.',
    approach:
      'Ingredient lists, dosage information and regulatory copy were moved out of description HTML into structured metafields, so each piece of data has a defined shape and renders into a designed component rather than arriving as arbitrary markup. Long-form regulatory content was placed in accordions built to the disclosure pattern — real buttons, correct expanded state, keyboard operable — so the information is available without dominating the page. Certification and testing signals were relocated to sit alongside the add-to-cart, which is where a hesitant customer is actually looking. The checkout was configured to carry the disclosures the product category requires.',
    outcome:
      'Regulatory information is now structured data rather than pasted markup, which means it renders consistently, can be updated without touching HTML, and cannot break the page layout. Trust signals appear at the point of decision instead of below the fold. The accordion implementation makes long compliance copy navigable rather than a wall of text customers scroll past.',
    stackRationale:
      'The accordions are hand-built rather than pulled from a component library specifically because the disclosure pattern is small and the accessibility requirements are exact — a library component would have needed as much configuration to meet them as writing it took, plus the payload.',
  },

  'mi-store-pakistan': {
    seoDescription:
      'Mi Store Pakistan — Core Web Vitals work on a high-traffic Shopify electronics store, targeting LCP and layout shift, by Munib Ahmad.',
    updatedAt: '2026-01-22',
    highlights: [
      'Largest Contentful Paint element identified and prioritised ahead of decorative assets',
      'Layout shift eliminated by reserving dimensions for every dynamically-inserted element',
      'Third-party scripts audited, deferred or removed based on measured cost',
      'Font loading changed to stop blocking first paint',
    ],
    problem:
      'Mi Store is a high-traffic consumer electronics retailer where a measurable share of sessions start from paid traffic, which makes load performance a direct cost. The store was failing Core Web Vitals on two axes: the Largest Contentful Paint element was competing for bandwidth with decorative carousel imagery that loaded first, and cumulative layout shift was significant because banners, badges and app-injected widgets were inserted after paint without reserved space, pushing content down as the page settled.',
    approach:
      'I started by identifying what the LCP element actually was on each template type — which turned out to differ between home, collection and product — and then made that element\'s delivery the priority, preloading it and demoting the decorative assets that had been ahead of it in the queue. Every element inserted after initial paint was given reserved dimensions, so the space is held from the first frame and later arrivals fill it rather than displacing what is already there. The third-party script list was audited against measured main-thread cost, and each script was deferred, loaded on interaction, or removed where its value did not justify what it cost. Font loading was changed so text renders immediately in a fallback rather than waiting on the webfont.',
    outcome:
      'The page now paints its most important content first rather than last, because the loading order reflects what the user is waiting for instead of the order things appear in the template. Layout stability improved to the point that content no longer moves under the cursor during load — the failure mode most likely to cause a mis-tap on mobile. Script cost is now a deliberate choice per script rather than an accumulated default.',
    stackRationale:
      'Most of this work was subtraction and reordering rather than new code, which is usually the right shape for a performance brief. The temptation on a store this size is to reach for a headless rebuild; the measurements showed the problem was loading priority and unreserved space, both fixable in the existing theme at a fraction of the cost and risk.',
  },

  'summat-official': {
    seoDescription:
      'Summat Official — Shopify boutique storefront for evening wear with HD lookbooks and variant selectors, by Munib Ahmad.',
    updatedAt: '2025-03-11',
    highlights: [
      'High-resolution lookbooks delivered responsively so quality never costs first paint',
      'Variant selector rebuilt to show fabric and colour rather than naming them',
      'Mobile purchase flow reduced to the steps that carry the decision',
      'Occasion-based collection structure layered over the standard catalogue',
    ],
    problem:
      'Summat sells evening and party wear, a category where the photography is the product — customers are buying based on drape, sheen and colour that a text variant name cannot convey. That put the brief in direct tension: the imagery needed to be high resolution, and the audience is overwhelmingly on mobile data. The existing store had resolved this tension by compromising the imagery, which undercut the thing customers were actually shopping for.',
    approach:
      'Rather than reducing image quality, I changed how it is delivered: responsive sources sized to real device breakpoints, modern formats where supported, and a loading order that lets the hero arrive at full quality while below-fold lookbook content waits its turn. The variant selector was rebuilt to show fabric and colour as visual swatches rather than naming them in a dropdown, which matches how the decision is actually made in this category. The mobile purchase flow was stripped back to the steps that carry the decision, removing interstitials that existed for desktop-era reasons. Collections were restructured around occasion, which is how customers in this category describe what they want, layered over the existing catalogue rather than replacing it.',
    outcome:
      'The store now presents its photography at the quality the category demands without that quality being paid for in initial load, because the cost has been moved to assets the customer has not scrolled to yet. Visual variant selection removed a step where customers previously had to guess what a colour name meant. Occasion-based browsing gave the catalogue an entry point that matches customer intent.',
    stackRationale:
      'Serving smaller images would have been the simple fix and the wrong one — for this category the imagery is the value proposition. Solving it through delivery rather than compression kept the brand intact and put the cost where it does not affect the first impression.',
  },

  'jafferjee-world': {
    seoDescription:
      'Jafferjee World — Shopify storefront for a 145-year-old leather house, with custom personalisation forms, by Munib Ahmad.',
    updatedAt: '2025-02-25',
    highlights: [
      'Personalisation options validated before they reach the cart, not after payment',
      'Monogram and foiling previews rendered from the customer\'s own input',
      'Line item properties carried through to fulfilment without manual re-entry',
      'Heritage narrative given structural space rather than a single About page',
    ],
    problem:
      'Jafferjee World is a 145-year-old leather goods house whose products are frequently personalised — gold foiling, embossing, monograms. Personalisation had been handled by collecting free-text in a note field and reconciling it manually after the order came in. That produced a steady stream of unfulfillable orders: monograms too long for the panel, character sets the foiling process cannot render, combinations that do not exist. Each one meant a support conversation and a delayed shipment.',
    approach:
      'I built the personalisation options as structured, validated inputs on the product form, with the constraints of the physical process encoded directly — character limits that match the panel, character sets restricted to what the foiling die can produce, combinations gated by what is actually available. The customer sees a preview rendered from their own input, so the result is visible before purchase rather than discovered on delivery. Validated values are carried through as line item properties, which means fulfilment reads them off the order rather than re-entering them from a note field. Separately, the brand\'s heritage was given real structural space across the storefront rather than being confined to an About page, since for a house of this age provenance is part of the product.',
    outcome:
      'Orders that cannot be fulfilled as specified are now caught at the point of entry rather than after payment, which removed the recurring support-and-delay cycle. Because the customer approves a preview of their own personalisation, expectation mismatches on delivery largely disappear. Fulfilment reads structured properties instead of interpreting free text, closing the transcription errors that manual re-entry introduced.',
    stackRationale:
      'Line item properties are a plain Shopify primitive and were sufficient here, which meant no third-party personalisation app in the critical path of every order. The validation rules encode physical manufacturing constraints, so they belong next to the product form where they can be kept in step with what the workshop can actually do.',
  },

  'easy-armour-online': {
    seoDescription:
      'Easy Armour Online — Shopify store for tactical and protective gear, with spec matrices and wholesale checkout, by Munib Ahmad.',
    updatedAt: '2025-01-28',
    highlights: [
      'Protection ratings and certifications presented as a comparable spec matrix',
      'Wholesale pricing tiers applied at the cart rather than through a separate storefront',
      'Bulk ordering interface built for quantity entry across many variants at once',
      'Product data structured so specifications are filterable, not just readable',
    ],
    problem:
      'Tactical and protective gear is bought on specification — protection rating, material, certification, weight — and those figures are the entire basis of comparison. The store was presenting them as prose in product descriptions, which made comparing two items a matter of reading two paragraphs and holding the numbers in your head. The store also serves wholesale buyers, who had been ordering by email because the retail cart could not express tiered pricing or bulk quantities across variants.',
    approach:
      'Specifications were restructured into typed, per-product fields so the same figure always occupies the same slot, rendered as a comparable matrix rather than prose. Because the data is now typed, it also became filterable — a buyer can narrow by protection rating directly instead of opening products to check. For wholesale, I implemented tiered pricing applied at the cart level, so a single storefront serves both audiences and the wholesale price is calculated from the actual basket rather than requiring a separate site. Bulk ordering was given a dedicated interface for entering quantities across many variants at once, which is how a wholesale order is actually composed.',
    outcome:
      'Specifications can now be compared at a glance and filtered on, turning the catalogue into something a buyer can navigate by requirement rather than by browsing. Wholesale orders moved from email into the store, which removed the manual quoting step and gave those customers self-service access to the same inventory data as retail.',
    stackRationale:
      'Running wholesale through cart-level pricing on one storefront, rather than standing up a second Shopify store, avoided splitting inventory across two systems. Two storefronts would have been cleaner to reason about and would have required inventory sync between them, which is the kind of moving part that eventually drifts.',
  },

  afrozeh: {
    seoDescription:
      'Afrozeh — Shopify performance engineering for a luxury fashion label: script optimisation, lazy loading and Klaviyo integration.',
    updatedAt: '2026-02-09',
    highlights: [
      'Render-blocking scripts moved off the critical path and loaded on interaction where possible',
      'Heavy banner structures lazy-loaded with reserved space to prevent shift',
      'Klaviyo integrated without adding a blocking script to first paint',
      'Third-party tag cost measured individually before any were kept',
    ],
    problem:
      'Afrozeh is a well-known luxury label whose storefront had accumulated the marketing stack that comes with that position: analytics, personalisation, reviews, email capture, several tag managers layered over each other. Each had been added for a defensible reason and none had been re-evaluated. The cumulative effect was that a significant portion of the main thread was occupied before the page became interactive, and the brand\'s large hero banner structures were competing with those scripts for the same early bandwidth.',
    approach:
      'I measured each third-party tag individually rather than treating the stack as a single block, which made the disproportionate offenders obvious — a small number of scripts were responsible for most of the blocking time. Those were moved off the critical path: deferred where order did not matter, loaded on first interaction where the feature is only needed after engagement, and removed outright where the tag was duplicating something another script already collected. The banner structures were converted to lazy loading with explicitly reserved dimensions, so they no longer compete for initial bandwidth and no longer shift content when they arrive. Klaviyo was integrated through its asynchronous path so email capture works without contributing a blocking request to first paint.',
    outcome:
      'The main thread is substantially freer during the window that determines whether the page feels fast, because the scripts that were occupying it either load later or no longer load at all. Banner imagery arrives without displacing content, removing the layout instability that had been most visible on the homepage. The marketing stack is now a set of individually-justified decisions rather than an accumulation.',
    stackRationale:
      'The instinct on a brand site this heavy is to move headless, and the measurement did not support it — the cost was in third-party scripts, which follow you to any frontend. Fixing the loading strategy addressed the actual cause; a rebuild would have been a large project that left the same tags blocking the same thread.',
  },

  qoffah: {
    seoDescription:
      'Qoffah — Shopify storefront with full right-to-left layout support, multilingual handling and localised shipping.',
    updatedAt: '2025-12-05',
    highlights: [
      'RTL implemented with CSS logical properties rather than a mirrored stylesheet',
      'Language switching that preserves the current page instead of returning home',
      'Localised shipping rules mapped to regional carrier behaviour',
      'Typography and numerals set appropriately per script',
    ],
    problem:
      'Qoffah serves a right-to-left market, and the usual approach — shipping a second, mirrored stylesheet — was not going to hold. Mirrored stylesheets drift: every new component has to be styled twice, and the RTL version is inevitably the one that gets forgotten. The store also needed genuine multilingual support, and the previous attempt sent anyone switching language back to the homepage, losing whatever they had been looking at.',
    approach:
      'Rather than mirroring, I rebuilt the layout on CSS logical properties — inline-start and inline-end in place of left and right — so direction is a document-level attribute and every component adapts automatically. New components inherit correct RTL behaviour by construction, which removes the class of bug where the LTR version is updated and the RTL version is not. Language switching was reworked to resolve the equivalent URL in the target language and navigate there, preserving context instead of dumping the visitor at the homepage. Shipping rules were mapped to how regional carriers actually operate, and typography was configured per script, since the type and numeral conventions that read well in one are not the ones that read well in the other.',
    outcome:
      'Right-to-left is now structural rather than a parallel stylesheet, which means it stays correct as the store grows instead of degrading with each addition. Switching language keeps the customer where they were, removing a navigation dead end that had been interrupting sessions. Regional shipping expectations now match what carriers actually do in that market.',
    stackRationale:
      'Logical properties require slightly more discipline up front than writing a mirrored stylesheet, and they are the difference between RTL support that survives maintenance and RTL support that rots. The mirrored approach is faster to ship and guarantees the drift problem.',
  },

  'mercer-retail': {
    seoDescription:
      'Mercer Retail — multi-brand Shopify architecture with flexible sections, lookbooks and automated inventory sync.',
    updatedAt: '2025-11-03',
    highlights: [
      'Brand identity expressed through data rather than per-brand template forks',
      'Homepage composed from interchangeable sections the client arranges themselves',
      'Inventory synchronisation automated across supplier feeds',
      'Schema architecture designed so adding a brand needs no new code',
    ],
    problem:
      'Mercer Retail carries several brands under one storefront, each with its own visual identity and its own supplier feed. The build it had been running forked the templates per brand, which meant any structural improvement had to be applied several times over and the versions had already diverged. Inventory came in from different suppliers in different shapes and was being reconciled by hand, which put the catalogue perpetually slightly behind reality.',
    approach:
      'I designed a schema where brand identity — colour, typography, layout emphasis, merchandising rules — is data attached to the brand, and the templates read from it. A single set of templates then renders every brand correctly, and adding a brand is a data entry task rather than a development one. The homepage was rebuilt from interchangeable sections that the client arranges in the admin, so seasonal restructuring does not require a developer. Inventory synchronisation was automated across the supplier feeds, normalising the differing formats into one internal shape so stock levels reflect reality without manual reconciliation.',
    outcome:
      'Structural improvements now land once and apply to every brand, which ended the divergence that forking had produced. The client restructures their own homepage seasonally without waiting on development. Inventory reflects supplier reality automatically, closing the gap that manual reconciliation had been leaving.',
    stackRationale:
      'Data-driven brand configuration costs more design work up front than forking templates, and forking is what produces a codebase where the same fix has to be made five times and is made in four. For a client whose model is explicitly to keep adding brands, the up-front cost pays back on the first addition.',
  },

  mizyanny: {
    seoDescription:
      'Mizyanny — bespoke Shopify apparel storefront with collection carousels, responsive filters and a sticky mobile cart.',
    updatedAt: '2025-10-17',
    highlights: [
      'Collection carousels built on native scroll snap rather than a carousel library',
      'Filters restructured to stay usable at mobile width',
      'Sticky cart summary that keeps the basket visible without covering content',
      'Product grid density tuned per breakpoint instead of scaled uniformly',
    ],
    problem:
      'Mizyanny\'s audience is almost entirely mobile, and the store had been built desktop-first and then adapted. The clearest symptom was filtering: the filter UI was a sidebar that, at phone width, became a full-screen takeover the customer had to commit to, apply, and dismiss before seeing any result. Carousels were running through a JavaScript library whose payload was disproportionate to what it did, and the cart was a page you navigated to, so customers lost their place every time they checked it.',
    approach:
      'Carousels were rebuilt on native CSS scroll snap, which gives the same interaction with no library, no JavaScript on the main thread, and correct momentum behaviour on touch, where library implementations tend to feel synthetic. Filters were restructured so that at mobile width they apply progressively and results update underneath, making filtering an exploratory action rather than a committed one. The cart became a sticky summary that keeps the basket visible without covering the content behind it. Grid density was tuned per breakpoint rather than scaling one layout, so each screen size gets a column count that suits it.',
    outcome:
      'Filtering became something customers do repeatedly while browsing rather than once at the start, because the cost of trying a filter dropped to nearly nothing. Removing the carousel library took a measurable amount of JavaScript off a page whose audience is on mobile data. The persistent cart removed the navigation break that had been ending browsing sessions.',
    stackRationale:
      'Native scroll snap is less configurable than a carousel library and handles this design entirely, with better touch behaviour because it is the platform\'s own scrolling rather than a reimplementation of it. Reaching for a library here would have meant paying in payload for flexibility the design does not use.',
  },

  'north-naturals': {
    seoDescription:
      'North Naturals — Shopify storefront for organic beauty, with ingredient transparency, reviews and fast page loads.',
    updatedAt: '2025-09-08',
    highlights: [
      'Ingredient sourcing surfaced as structured, comparable data',
      'Review content rendered server-side rather than injected by a widget',
      'Restrained palette carried through a token layer for consistency',
      'Certification claims placed next to the products they apply to',
    ],
    problem:
      'Organic beauty is a category where the customer is specifically checking claims — what is in it, where it came from, who certified it — and where scepticism is the default posture. North Naturals had the information but it lived in prose, so two products could not be compared without reading both. Reviews were arriving through a third-party widget that injected content after page load, which meant the social proof the brand most needed was both invisible to search engines and late to appear for customers.',
    approach:
      'Ingredient and sourcing data were restructured into typed fields so the same claim occupies the same position on every product and two items can be compared directly. Review content was moved to server-side rendering, which puts it in the initial HTML — visible immediately, and readable by search engines as part of the page rather than as a later injection. The palette was deliberately restrained and driven from a token layer so the green-and-neutral identity stays consistent across every surface without being re-specified per component. Certification claims were placed adjacent to the products they actually apply to, rather than presented site-wide where they imply broader coverage than they have.',
    outcome:
      'Ingredient claims are now comparable rather than narrative, which serves a customer who is actively evaluating rather than browsing. Reviews are present in the initial render, so they contribute to search visibility and appear without the delay that had made them easy to miss. Certification claims are scoped accurately to the products that carry them.',
    stackRationale:
      'Server-rendering reviews meant giving up the drop-in convenience of the widget in exchange for content that exists in the HTML. For a brand whose conversion depends on social proof and whose acquisition depends on search, content that only exists after JavaScript runs is content that does not fully count.',
  },

  shoestreet: {
    seoDescription:
      'Shoestreet — conversion-focused Shopify footwear storefront with responsive grids and streamlined mobile checkout.',
    updatedAt: '2026-03-02',
    highlights: [
      'Size availability shown on the product card before the customer commits to a click',
      'Checkout reduced to the minimum steps the order genuinely requires',
      'Collection grids tuned for scan-ability at thumb distance',
      'Local payment and delivery expectations set on the product page',
    ],
    problem:
      'Footwear has an unusually high rate of interest that dies at the size step: a customer finds a shoe, clicks through, and discovers their size is unavailable. Shoestreet was showing size availability only on the product page, so a meaningful share of clicks were being spent to deliver bad news. The checkout had also accumulated steps — an account prompt, a newsletter interstitial, an upsell — each of which was an opportunity to leave.',
    approach:
      'Size availability was surfaced onto the collection card itself, so a customer sees whether their size exists before spending a click. That is a small change in placement and a large change in how the catalogue feels to browse. The checkout was cut back to the steps the order actually requires: the account prompt became optional and post-purchase, the newsletter capture moved to the confirmation page where it does not compete with completing the order, and the upsell was removed from the path entirely. Collection grids were tuned for scanning at thumb distance rather than for desktop density. Local payment methods and realistic delivery expectations were stated on the product page, since both are decision factors in this market.',
    outcome:
      'Customers stop spending clicks discovering that their size is unavailable, which makes the catalogue faster to browse and less frustrating. The checkout no longer interrupts a completed decision with requests that could wait — the newsletter still gets its opportunity, after the order rather than during it.',
    stackRationale:
      'Putting inventory state on the collection card means the collection query has to carry variant-level data, which is slightly more expensive per request. That cost is trivially worth paying to avoid a click-through that ends in disappointment, which costs both a page load and the customer\'s patience.',
  },

  // ── GoHighLevel ─────────────────────────────────────────────────
  'strong-refuge-pool-community': {
    seoDescription:
      'Strong Refuge Pool Community — GoHighLevel recruitment funnel with automated onboarding and webhook notifications.',
    updatedAt: '2025-08-27',
    highlights: [
      'Onboarding sequence branches on how the member joined, not one path for everyone',
      'Webhook notifications routed to the right person by enquiry type',
      'Access tags applied automatically so membership state drives what a member sees',
      'Form kept short enough to complete on a phone in one sitting',
    ],
    problem:
      'The community recruitment page was collecting sign-ups into a single undifferentiated list, and everything downstream was manual: someone read each entry, decided who should handle it, and forwarded it. That worked at low volume and broke as the community grew — response times stretched, entries were missed, and the same welcome message went to people arriving through completely different routes.',
    approach:
      'I rebuilt the funnel so that the route a member arrives through is captured as data and drives what happens next, rather than being lost at submission. Onboarding branches on that data, so someone joining through a referral gets a different sequence from someone arriving cold. Webhook notifications are routed by enquiry type directly to the person who handles that type, removing the human triage step that had become the bottleneck. Access tags are applied automatically based on the submission, so membership state controls what a member can see without anyone setting it by hand. The form itself was cut back to what is genuinely needed at first contact, on the reasoning that a shorter form completed is worth more than a longer one abandoned.',
    outcome:
      'Sign-ups now reach the right person without passing through a manual triage step, which is what had been determining response time. New members receive a sequence that matches how they arrived rather than a generic welcome. Access state is set by the system at the moment of joining instead of by someone remembering to set it.',
    stackRationale:
      'Keeping routing logic inside GoHighLevel rather than pushing it to an external automation tool meant the client can see and change it in the same place they manage everything else. An external orchestrator would have been more capable and would have put the logic somewhere the client cannot inspect when something looks wrong.',
  },

  'strong-refuge-pool-funnel': {
    seoDescription:
      'Strong Refuge Pool — high-converting GoHighLevel lead funnel with booking calendars and SMS follow-up automation.',
    updatedAt: '2025-07-15',
    highlights: [
      'Booking calendar embedded in the funnel rather than linked out to a separate tool',
      'SMS follow-up timed against booking state instead of on a fixed schedule',
      'Form fields reduced to what qualifies a lead, with the rest deferred to the call',
      'Every step instrumented so drop-off is attributable to a specific point',
    ],
    problem:
      'The lead funnel was converting below what the traffic quality suggested it should, and there was no instrumentation to say where it was losing people. The form asked for enough information to fully qualify a lead up front, which is a lot to ask before any value has been demonstrated. Booking happened on an external scheduling tool, so the highest-intent moment in the whole funnel involved leaving the page. Follow-up SMS ran on a fixed schedule regardless of whether the lead had already booked.',
    approach:
      'First I instrumented every step, so drop-off could be attributed rather than guessed at — that immediately showed the form and the booking hand-off as the two largest losses. The form was cut to the fields that actually qualify a lead, with everything else deferred to the call where it is a conversation instead of a chore. Booking was embedded directly in the funnel, so the highest-intent moment no longer requires a context switch to another domain. SMS follow-up was rewired to trigger on booking state, so someone who has already booked stops receiving reminders to book — which had been the most common complaint.',
    outcome:
      'Drop-off is now attributable to a specific step, which turns funnel improvement from guesswork into a queue of known problems. Booking happens in-page at the moment of intent rather than after a hand-off. Follow-up messaging reflects what the lead has actually done, which removed the sequence that had been messaging people about something they had already completed.',
    stackRationale:
      'Embedding the calendar rather than linking to the external tool meant accepting GoHighLevel\'s native scheduling and its constraints instead of the more featureful dedicated tool. At the highest-intent step of a funnel, removing a context switch is worth more than the features being given up.',
  },

  'strong-refuge-pool-compliance': {
    seoDescription:
      'Strong Refuge Pool Compliance — GoHighLevel legal disclosure and evaluation templates built mobile-first.',
    updatedAt: '2025-06-09',
    highlights: [
      'Legal copy typeset for readability rather than compressed to fit above the fold',
      'Evaluation forms structured in sections so long documents stay navigable',
      'Mobile-first layout because these are completed on site, on a phone',
      'Completion state preserved so a long form survives an interruption',
    ],
    problem:
      'Compliance and evaluation documents are completed by technicians standing at a pool site, on a phone, often with one hand. The existing templates had been laid out for desktop and shrunk, which produced small text, cramped touch targets, and a single long scroll with no sense of progress. Worse, an interrupted form lost its contents — and interruption is the normal case for someone doing this between tasks.',
    approach:
      'I rebuilt the templates mobile-first, treating the phone as the primary case rather than the degraded one. Legal copy was typeset for actual readability — line length, size and spacing chosen to be read rather than to fit — on the reasoning that a disclosure nobody can read does not do its job regardless of whether it is technically present. Long evaluation forms were broken into sections with visible progress, so the technician knows how much remains. Completion state is preserved as the form is filled, so an interruption does not mean starting over. Touch targets were sized for use with one hand in the field, not for a mouse.',
    outcome:
      'The forms are now usable in the conditions they are actually used in, which was the gap between the previous version working in testing and failing in the field. Preserved state removed the failure that had been causing partial submissions and repeated work. Sectioned progress makes a long form feel finite.',
    stackRationale:
      'Building mobile-first rather than adapting the desktop layout meant redoing work that technically already existed. Adapted-desktop was the reason the small text and cramped targets were there in the first place — inverting the starting assumption was the fix, not a refinement of it.',
  },

  'strong-refuge-pool-equipment': {
    seoDescription:
      'Strong Refuge Pool Equipment — GoHighLevel operations portal mapping inventory forms to CRM data.',
    updatedAt: '2025-05-02',
    highlights: [
      'Inventory requests mapped to CRM records so equipment history is queryable',
      'Procurement forms validated against what is actually orderable',
      'Internal portal separated from the public-facing funnels',
      'Request state visible to the requester without an email chase',
    ],
    problem:
      'Equipment procurement was running on email and a spreadsheet. Requests were free-text, which meant they regularly named equipment that was discontinued or specified incompatible combinations, and each one had to be checked by hand. Nobody could answer "what equipment is at this site and when was it last serviced" without reconstructing it from email history, and requesters had no way to see the status of their own request short of asking.',
    approach:
      'I built the procurement flow as structured forms validated against what is genuinely orderable, so unavailable or incompatible requests are caught at entry rather than during review. Each request is mapped onto the CRM record for the site it concerns, which means equipment history accumulates as a queryable property of the site rather than as scattered email. The internal portal was kept architecturally separate from the public-facing funnels, since conflating internal tooling with lead capture is how internal data ends up somewhere it should not be. Request state was made visible to the requester, removing the status-chase email entirely.',
    outcome:
      'Procurement requests arrive valid, so the manual checking step that used to precede every order is no longer needed. Equipment history is now a property of the site record and can be answered by looking rather than by reconstruction. Requesters can see their own request status, which removed a recurring category of internal email.',
    stackRationale:
      'Mapping requests onto existing CRM records rather than standing up a separate inventory system meant working within GoHighLevel\'s data model, which is not built for asset tracking. It keeps everything in one system the client already operates — a dedicated tool would model assets better and would be a second system to maintain, license and sync.',
  },

  'wingman-aero-uft': {
    seoDescription:
      'Wingman Aero UFT — GoHighLevel application funnel for aviation training, with multi-step forms and CRM automation.',
    updatedAt: '2026-01-14',
    highlights: [
      'Multi-step application that saves progress between sessions',
      'Eligibility logic branches the form so candidates only see relevant questions',
      'Applications routed into CRM pipelines by programme and readiness',
      'Document upload handled in-flow rather than by follow-up email',
    ],
    problem:
      'Aviation training applications are long by necessity — eligibility depends on medical certification, prior hours, licensing status and programme fit. Presenting that as a single form guaranteed abandonment, and presenting the same questions to every applicant meant most people answered a large number of questions irrelevant to their situation. Supporting documents were being collected afterwards by email, which put a manual chase between application and assessment.',
    approach:
      'The application was rebuilt as a multi-step flow that saves progress, so a candidate can start it, gather the certificate numbers they do not have to hand, and return without losing their place. Eligibility logic branches the form, so answering an early question about licensing status determines which later sections appear — most applicants now see a substantially shorter form than the full question set. Completed applications route into CRM pipelines segmented by programme and readiness, so assessment starts with applications already sorted. Document upload was moved into the flow itself, so supporting evidence arrives attached to the application rather than through a subsequent email exchange.',
    outcome:
      'Candidates can complete a genuinely long application across more than one sitting, which removes the abandonment that a single-session form was forcing. Branching means each applicant answers their own questions rather than everyone\'s. Applications arrive complete and pre-sorted, which removed both the document chase and the manual triage that preceded assessment.',
    stackRationale:
      'Progress saving inside GoHighLevel\'s form system required working within its state handling rather than building a custom application backend. A bespoke backend would have given finer control over the flow and would have sat outside the CRM the admissions team works in — the sorting and pipeline benefits depend on the application living in the same system as everything downstream of it.',
  },

  'beyond-remedy-ny-injectables': {
    seoDescription:
      'Beyond Remedy NY — GoHighLevel promotional funnel for a medical spa, with booking automation and review integration.',
    updatedAt: '2025-04-03',
    highlights: [
      'Promotional deadline driven by real campaign data, not a resetting timer',
      'Booking confirmation and reminders automated from the appointment record',
      'Reviews integrated as evidence next to the specific treatment they concern',
      'Treatment information presented at the depth the decision requires',
    ],
    problem:
      'The promotional page relied on a countdown timer that reset on every page load, which is transparent to anyone who has seen it before and corrosive to trust in a category where trust is the entire purchase decision. Reviews were presented as a generic carousel unconnected to the treatments they discussed. Booking confirmations were sent manually, so confirmation timing depended on whether someone was at a desk.',
    approach:
      'The countdown was rebuilt against the actual campaign end date, so it reflects something real and reads as credible because it is. Reviews were re-associated with the specific treatments they discuss and placed next to those treatments, which turns generic social proof into relevant evidence at the point of decision. Booking confirmation and reminder messaging was automated from the appointment record, so confirmation arrives immediately regardless of staffing, and reminders fire against the appointment rather than on a schedule someone maintains. Treatment information was expanded to the depth the decision actually requires in a medical category, rather than the promotional summary it had been.',
    outcome:
      'The urgency on the page is now real, which matters more than whether it is high — a deadline that survives a page refresh is one a returning visitor can believe. Reviews appear as specific evidence rather than decoration. Confirmation is immediate, which closes the window where a booked customer was left uncertain whether their booking had registered.',
    stackRationale:
      'Tying the countdown to real campaign data constrains marketing to actual deadlines instead of perpetual urgency. In a medical category the credibility cost of a visibly fake timer outweighs whatever conversion the false urgency was buying, particularly for returning visitors who are the most likely to convert.',
  },

  'beyond-remedy-co-main': {
    seoDescription:
      'Beyond Remedy Co — GoHighLevel lead acquisition funnel with intake forms, email automation and calendar booking.',
    updatedAt: '2025-03-20',
    highlights: [
      'Intake form structured around the consultation that follows it',
      'Email sequences branch on stated interest rather than sending one nurture path',
      'Calendar availability reflects real staff schedules',
      'Staff notifications carry enough context to act without opening the CRM',
    ],
    problem:
      'The main acquisition funnel was collecting leads into one pool and sending everyone the same nurture sequence, regardless of what they had come for. Intake questions had been designed around what was easy to ask rather than what the consultation actually needs, so consultations began by re-gathering information the lead had already provided. Calendar availability was maintained separately from staff schedules and drifted, producing double-bookings.',
    approach:
      'I restructured the intake form around what the consultation genuinely needs, so the person taking the call starts with useful context instead of a form\'s worth of questions to repeat. Email sequences were branched on stated interest, replacing the single nurture path with content that corresponds to what the lead actually asked about. Calendar availability was connected to real staff schedules rather than maintained as a parallel copy, which is what had been producing the double-bookings. Staff notifications were rewritten to carry enough context that the recipient can act directly, instead of being a prompt to go and look the lead up.',
    outcome:
      'Consultations now start from what the lead already told the form rather than from scratch. Nurture content matches stated interest, which is the difference between a sequence that reads as relevant and one that reads as a mailing list. Availability reflects reality, so the double-booking failure — the most damaging kind, because it is discovered by the customer — no longer occurs.',
    stackRationale:
      'Connecting the calendar to live staff schedules rather than maintaining a curated availability window gave up fine control over which slots get offered. Any manually-maintained copy of a schedule will drift from the real one, and a booking system that drifts is worse than one that offers fewer slots.',
  },

  'swoon-learning-start': {
    seoDescription:
      'Swoon Learning — GoHighLevel onboarding portal for an EdTech service, with pricing tiers and automated profile setup.',
    updatedAt: '2025-02-11',
    highlights: [
      'Pricing presented so tiers are comparable rather than listed',
      'Teacher and student onboarding follow separate paths from the first step',
      'Profile creation triggered automatically on completed signup',
      'Onboarding progress visible so an interrupted setup can be resumed',
    ],
    problem:
      'Swoon Learning onboards two distinct audiences — teachers and students — whose needs diverge from the very first step, and both were being pushed through one generic flow that served neither well. Pricing was presented as three separate blocks with no shared axis, so comparing tiers meant reading all three and building the comparison yourself. Profile creation was manual after signup, which inserted a delay between a customer paying and being able to use the thing they paid for.',
    approach:
      'The onboarding flow was split at the first step, so teachers and students follow paths built for them rather than a compromise between the two. Pricing was rebuilt as a comparison structured on shared axes, so the differences between tiers are readable at a glance instead of requiring the visitor to construct the comparison. Profile creation was automated to trigger on completed signup, closing the gap between payment and access. Onboarding progress was made visible and resumable, since setup for either audience spans more than one sitting in practice.',
    outcome:
      'Each audience now follows a flow designed for it, which removes the questions that a generic path made unavoidable. Pricing tiers can be compared directly rather than reconstructed. Access follows payment automatically, eliminating the delay that had been the first experience of the product for every new customer.',
    stackRationale:
      'Splitting the flow means maintaining two onboarding paths rather than one. That is genuinely more surface area, and it is the right cost here because the two audiences diverge immediately and completely — a single path serving both was not a simplification, it was a compromise that served neither.',
  },

  'my-injury-case-help': {
    seoDescription:
      'My Injury Case Help — GoHighLevel legal intake funnel with qualification logic and instant SMS notification.',
    updatedAt: '2025-12-19',
    highlights: [
      'Qualification logic filters cases before they reach a legal representative',
      'Instant SMS and email notification on qualified submissions',
      'Intake questions ordered by what determines viability, not by convenience',
      'Sensitive information handled with disclosure of how it will be used',
    ],
    problem:
      'Legal intake has a timing property that most lead capture does not: response speed materially affects whether a case is retained, because a potential client contacting several firms generally goes with whoever responds first. This funnel was capturing every enquiry undifferentiated and notifying by email, so representatives spent their attention on cases that were never viable while the viable ones waited in the same queue.',
    approach:
      'I built multi-tier qualification logic into the intake itself, ordered so that the questions determining viability come first — if a case fails on jurisdiction or timing, that is established in the first few answers rather than after a full form. Qualified submissions trigger immediate SMS and email notification to a representative, because the speed advantage only exists if the notification arrives faster than a competitor\'s. Unqualified enquiries are handled with a clear response rather than silence, which is both the decent outcome and avoids the reputational cost of appearing to ignore people. Given the sensitivity of what is being collected, the intake states plainly what happens to the information.',
    outcome:
      'Representative attention now goes to cases that can actually proceed, because the filtering happens before the notification rather than after it. Qualified enquiries generate an immediate SMS, which is what the retention advantage in this category actually depends on. Enquiries that do not qualify receive an answer instead of nothing.',
    stackRationale:
      'Front-loading the qualifying questions risks losing people who would have completed a gentler form, and that is the correct risk to take here: a longer form completed by a viable case is worth more than a short one completed by a case that cannot proceed. The SMS notification exists because email latency is measured in minutes and the competitive window in this category is shorter than that.',
  },
};

/** Case-study content for a slug, or undefined if none has been written yet. */
export function getCaseStudy(slug: string): CaseStudy | undefined {
  return caseStudies[slug];
}
